### ISSUE TITLE
Configuring the header name?

### ISSUE THREAD

**Issue by alturkovic** [rabbitmq/rabbitmq-routing-node-stamp#12]
Currently, this plugin writes the routing node in the "x-routed-by" header. I would like to use this header for routing logic using the header exchange. Unfortunately, the header exchange cannot route using using any "x-" headers.
Is there a way to configure the header name this plugin uses without building it myself?

**Comment by michaelklishin** [comment]
There is no. This plugin operates on the hottest code path possible so fetching values from application configuration is not an option (all those requests go through a single process in Erlang/OTP). There isn't enough interest in such a feature to justify messing with channel interceptor state. This plugin is incredibly small and simple and perhaps should stay this way.

It should be easy enough to develop your own version for those who really need it.
