### ISSUE TITLE
Please enable support for RabbitMQ 3.9

### ISSUE THREAD

**Issue by chadknutson** [rabbitmq/rabbitmq-routing-node-stamp#15]
Latest release is not supported by RabbitMQ 3.9.  Can you please create a new release for it?  Thanks!

**Comment by lukebakken** [comment]
Will do!

**Comment by lukebakken** [comment]
@chadknutson please give this a try in your environment -

https://github.com/rabbitmq/rabbitmq-routing-node-stamp/releases/tag/v3.9.0-rc1

Report back and I will produce an official release! Thank you.

**Comment by chadknutson** [comment]
I tested the plugin in RabbitMQ 3.9.11 and 3.9.13.  It worked as expected for both versions.  Thank you very much @lukebakken!

**Comment by lukebakken** [comment]
I appreciate the follow-up.

https://github.com/rabbitmq/rabbitmq-routing-node-stamp/releases/tag/v3.9.0
