### ISSUE TITLE
Release with fixed version constraint for 3.10 series

### ISSUE THREAD

**Issue by gomoripeti** [rabbitmq/rabbitmq-routing-node-stamp#18]
Could you please release a version of this plugin that includes https://github.com/rabbitmq/rabbitmq-routing-node-stamp/commit/379bb1860a2e8b7d8c03ad8c7f71e98f909c4ed6

**Comment by lukebakken** [comment]
If you have time to test out PR #19, that would be great. I used Erlang 24.2 and Elixir 1.13.4-otp24 in my environment.

```
make
make DIST_AS_EZS=true dist
```

The above will create the plugin in the `plugins/` dir, then you can verify the fix in your env.

**Comment by lukebakken** [comment]
@michaelklishin I'll get the new release today.

**Comment by gomoripeti** [comment]
thanks, building from the `v3.10.x` branch with #19 merged works for me.

**Comment by lukebakken** [comment]
Fixed by #19

**Comment by lukebakken** [comment]
https://github.com/rabbitmq/rabbitmq-routing-node-stamp/releases/tag/v3.10.x-1
